# Generated by Django 4.2.4 on 2023-09-30 03:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_referral_message"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Referral",
            new_name="Reference",
        ),
    ]
